version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    groups:
      actions:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: direct
    cooldown:
      default-days: 14
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
