version: 1
labels:

- label: enhancement
  title: ^feat\b

- label: bug
  title: ^fix\b

- label: documentation
  title: ^docs\b

- label: chore
  title: ^chore\b

- label: chore
  title: ^refactor\b

- label: build
  title: ^build\b

- label: dependencies
  title: ^build\(deps\)\b
