comment: false

coverage:
  range: "40...100"
  precision: 1
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true

ignore:
  - "**.pb.go"
  - "**_mocked.go"
  - "**/mocks/*"
