version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - mnd
    - musttag
    - nestif
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - protogetter
    - recvcheck
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - usetesting # go 1.24
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/gen
      - internal/db/olddb
      - cmd/dev
      - repos
      - third_party$
      - builtin$
      - examples$
      - _test\.go$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - internal/gen
      - cmd/dev
      - repos
      - third_party$
      - builtin$
      - examples$
