version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustive
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - gomoddirectives
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - nestif
    - nonamedreturns
    - paralleltest
    - protogetter
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/gen
      - cmd/dev
      - repos
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - internal/gen
      - cmd/dev
      - repos
      - third_party$
      - builtin$
      - examples$
