ARG GOVERSION=latest
FROM golang:$GOVERSION AS builder

WORKDIR /src
COPY . .

ENV CGO_ENABLED=0
ENV BUILD_HOST=syncthing.net
ENV BUILD_USER=docker
RUN rm -f stcrashreceiver && go run build.go build stcrashreceiver

FROM alpine

EXPOSE 8080

COPY --from=builder /src/stcrashreceiver /bin/stcrashreceiver

ENTRYPOINT [ "/bin/stcrashreceiver" ]
