#!/bin/bash

archs=( i386:386: amd64:amd64: arm:arm: aarch64:arm64:armv8 ppc64le:ppc64le: s390x:s390x: )
manifests=()

# push individual tags
for arch in "${archs[@]}"
do
  parts=( ${arch//:/ } )

  docker push "${IMAGE_NAME/:/:${parts[0]}-}"
  manifests+=("${IMAGE_NAME/:/:${parts[0]}-}")
done

# create manifest
docker manifest create $IMAGE_NAME $manifests

# annotate manifest
for arch in "${archs[@]}"
do
  parts=( ${arch//:/ } )

  if [ "${parts[2]}" == "" ]
  then
    docker manifest annotate $IMAGE_NAME "${IMAGE_NAME/:/:${parts[0]}-}" --os linux --arch ${parts[1]}
  else
    docker manifest annotate $IMAGE_NAME "${IMAGE_NAME/:/:${parts[0]}-}" --os linux --arch ${parts[1]} --variant ${parts[2]}
  fi
done

# push manifest
docker manifest push $IMAGE_NAME
