// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lib/config/guiconfiguration.proto

package config

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/syncthing/syncthing/proto/ext"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GUIConfiguration struct {
	Enabled                   bool                 `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled" xml:"enabled,attr" default:"true"`
	RawAddress                string               `protobuf:"bytes,2,opt,name=address,proto3" json:"address" xml:"address" default:"127.0.0.1:8384"`
	RawUnixSocketPermissions  string               `protobuf:"bytes,3,opt,name=unix_socket_permissions,json=unixSocketPermissions,proto3" json:"unixSocketPermissions" xml:"unixSocketPermissions,omitempty"`
	User                      string               `protobuf:"bytes,4,opt,name=user,proto3" json:"user" xml:"user,omitempty"`
	Password                  string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password" xml:"password,omitempty"`
	AuthMode                  AuthMode             `protobuf:"varint,6,opt,name=auth_mode,json=authMode,proto3,enum=config.AuthMode" json:"authMode" xml:"authMode,omitempty"`
	RawUseTLS                 bool                 `protobuf:"varint,7,opt,name=use_tls,json=useTls,proto3" json:"useTLS" xml:"tls,attr"`
	APIKey                    string               `protobuf:"bytes,8,opt,name=api_key,json=apiKey,proto3" json:"apiKey" xml:"apikey,omitempty"`
	InsecureAdminAccess       bool                 `protobuf:"varint,9,opt,name=insecure_admin_access,json=insecureAdminAccess,proto3" json:"insecureAdminAccess" xml:"insecureAdminAccess,omitempty"`
	Theme                     string               `protobuf:"bytes,10,opt,name=theme,proto3" json:"theme" xml:"theme" default:"default"`
	Debugging                 bool                 `protobuf:"varint,11,opt,name=debugging,proto3" json:"debugging" xml:"debugging,attr"`
	InsecureSkipHostCheck     bool                 `protobuf:"varint,12,opt,name=insecure_skip_host_check,json=insecureSkipHostCheck,proto3" json:"insecureSkipHostcheck" xml:"insecureSkipHostcheck,omitempty"`
	InsecureAllowFrameLoading bool                 `protobuf:"varint,13,opt,name=insecure_allow_frame_loading,json=insecureAllowFrameLoading,proto3" json:"insecureAllowFrameLoading" xml:"insecureAllowFrameLoading,omitempty"`
	SendBasicAuthPrompt       bool                 `protobuf:"varint,14,opt,name=send_basic_auth_prompt,json=sendBasicAuthPrompt,proto3" json:"sendBasicAuthPrompt" xml:"sendBasicAuthPrompt,attr"`
	WebauthnUserId            string               `protobuf:"bytes,15,opt,name=webauthn_user_id,json=webauthnUserId,proto3" json:"webauthnUserId" xml:"webauthnUserId"`
	WebauthnRpId              string               `protobuf:"bytes,16,opt,name=webauthn_rp_id,json=webauthnRpId,proto3" json:"webauthnRpId" xml:"webauthnRpId" default:"localhost"`
	WebauthnOrigin            string               `protobuf:"bytes,17,opt,name=webauthn_origin,json=webauthnOrigin,proto3" json:"webauthnOrigin" xml:"webauthnOrigin" default:"https://localhost:8384"`
	WebauthnCredentials       []WebauthnCredential `protobuf:"bytes,18,rep,name=webauthn_credentials,json=webauthnCredentials,proto3" json:"_webauthnCredentials" xml:"webauthnCredential"`
}

func (m *GUIConfiguration) Reset()         { *m = GUIConfiguration{} }
func (m *GUIConfiguration) String() string { return proto.CompactTextString(m) }
func (*GUIConfiguration) ProtoMessage()    {}
func (*GUIConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9586d611855d64, []int{0}
}
func (m *GUIConfiguration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GUIConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GUIConfiguration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GUIConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GUIConfiguration.Merge(m, src)
}
func (m *GUIConfiguration) XXX_Size() int {
	return m.ProtoSize()
}
func (m *GUIConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_GUIConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_GUIConfiguration proto.InternalMessageInfo

type WebauthnCredential struct {
	ID            string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id" xml:"id,attr"`
	RpId          string    `protobuf:"bytes,2,opt,name=rp_id,json=rpId,proto3" json:"rpId" xml:"rpId,attr"`
	Nickname      string    `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname" xml:"nickname,attr"`
	PublicKeyCose string    `protobuf:"bytes,4,opt,name=public_key_cose,json=publicKeyCose,proto3" json:"publicKeyCose" xml:"publicKeyCose,attr"`
	SignCount     uint32    `protobuf:"varint,5,opt,name=sign_count,json=signCount,proto3" json:"signCount" xml:"signCount,attr"`
	Transports    []string  `protobuf:"bytes,6,rep,name=transports,proto3" json:"transports" xml:"transports,attr"`
	RequireUv     bool      `protobuf:"varint,7,opt,name=require_uv,json=requireUv,proto3" json:"requireUv" xml:"requireUv,attr"`
	CreateTime    time.Time `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3,stdtime" json:"createTime" xml:"createTime,attr"`
	LastUseTime   time.Time `protobuf:"bytes,9,opt,name=last_use_time,json=lastUseTime,proto3,stdtime" json:"lastUseTime" xml:"lastUseTime,attr"`
}

func (m *WebauthnCredential) Reset()         { *m = WebauthnCredential{} }
func (m *WebauthnCredential) String() string { return proto.CompactTextString(m) }
func (*WebauthnCredential) ProtoMessage()    {}
func (*WebauthnCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9586d611855d64, []int{1}
}
func (m *WebauthnCredential) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebauthnCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WebauthnCredential.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WebauthnCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebauthnCredential.Merge(m, src)
}
func (m *WebauthnCredential) XXX_Size() int {
	return m.ProtoSize()
}
func (m *WebauthnCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_WebauthnCredential.DiscardUnknown(m)
}

var xxx_messageInfo_WebauthnCredential proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GUIConfiguration)(nil), "config.GUIConfiguration")
	proto.RegisterType((*WebauthnCredential)(nil), "config.WebauthnCredential")
}

func init() { proto.RegisterFile("lib/config/guiconfiguration.proto", fileDescriptor_2a9586d611855d64) }

var fileDescriptor_2a9586d611855d64 = []byte{
	// 1434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xcf, 0x6f, 0xd4, 0x48,
	0x16, 0x8e, 0x03, 0x24, 0xe9, 0x0a, 0xf9, 0xb1, 0xc5, 0x8f, 0x35, 0x68, 0xe9, 0x0a, 0xa1, 0x17,
	0x05, 0x09, 0x75, 0x20, 0x80, 0x40, 0xd1, 0x2e, 0x52, 0x3a, 0x2c, 0x4b, 0x14, 0x56, 0x1b, 0x19,
	0xb2, 0x48, 0x5c, 0x2c, 0xb7, 0x5d, 0xe9, 0x2e, 0xb5, 0xdb, 0x36, 0x2e, 0x9b, 0x24, 0x07, 0x76,
	0x4e, 0x73, 0x99, 0x13, 0xca, 0x9c, 0x47, 0xe2, 0x36, 0xf7, 0x91, 0x46, 0xf3, 0x2f, 0x70, 0xeb,
	0x3e, 0x8d, 0xe6, 0x54, 0x23, 0x92, 0xc3, 0x48, 0x3e, 0xfa, 0x98, 0xd3, 0xa8, 0xaa, 0xec, 0x6a,
	0xbb, 0xbb, 0x19, 0xe6, 0x56, 0xf5, 0xbd, 0xef, 0xbd, 0xf7, 0x55, 0xf9, 0xbd, 0xae, 0xd7, 0xe0,
	0xba, 0x4b, 0x9a, 0xab, 0xb6, 0xef, 0xed, 0x91, 0xd6, 0x6a, 0x2b, 0x26, 0x72, 0x15, 0x87, 0x56,
	0x44, 0x7c, 0xaf, 0x1e, 0x84, 0x7e, 0xe4, 0xc3, 0x29, 0x09, 0x5e, 0x45, 0x2d, 0xdf, 0x6f, 0xb9,
	0x78, 0x55, 0xa0, 0xcd, 0x78, 0x6f, 0x35, 0x22, 0x5d, 0x4c, 0x23, 0xab, 0x1b, 0x48, 0xe2, 0xd5,
	0x2b, 0x85, 0x58, 0x56, 0x1c, 0xb5, 0xbb, 0xbe, 0x83, 0x33, 0x53, 0x05, 0x1f, 0x44, 0x72, 0xb9,
	0xfc, 0x3d, 0x04, 0x8b, 0xff, 0xde, 0xdd, 0xda, 0x2c, 0x66, 0x82, 0x4d, 0x30, 0x8d, 0x3d, 0xab,
	0xe9, 0x62, 0x47, 0xd7, 0x96, 0xb4, 0x95, 0x99, 0xc6, 0xb3, 0x84, 0xa1, 0x1c, 0x4a, 0x19, 0xba,
	0x7e, 0xd0, 0x75, 0xd7, 0x97, 0xb3, 0xfd, 0x6d, 0x2b, 0x8a, 0xc2, 0xe5, 0x25, 0x07, 0xef, 0x59,
	0xb1, 0x1b, 0xad, 0x2f, 0x47, 0x61, 0x8c, 0x97, 0x93, 0x5e, 0xed, 0x7c, 0xd1, 0x7e, 0xda, 0xab,
	0x9d, 0xe5, 0x06, 0x23, 0x8f, 0x02, 0xdf, 0x81, 0x69, 0xcb, 0x71, 0x42, 0x4c, 0xa9, 0x3e, 0xb9,
	0xa4, 0xad, 0x54, 0x1a, 0xf6, 0x31, 0x43, 0xc0, 0xb0, 0xf6, 0x37, 0x24, 0xca, 0x33, 0x66, 0x84,
	0x94, 0xa1, 0x9b, 0x22, 0x63, 0xb6, 0x2f, 0x24, 0xbb, 0xbb, 0xf6, 0xb0, 0x7e, 0xa7, 0x7e, 0xa7,
	0x7e, 0x77, 0xfd, 0xd1, 0xbd, 0x47, 0xf7, 0x97, 0x4f, 0x7b, 0xb5, 0xf9, 0x32, 0x74, 0xd4, 0xaf,
	0x15, 0x82, 0x1a, 0x79, 0x48, 0xf8, 0xb3, 0x06, 0xfe, 0x1a, 0x7b, 0xe4, 0xc0, 0xa4, 0xbe, 0xdd,
	0xc1, 0x91, 0x19, 0xe0, 0xb0, 0x4b, 0x28, 0x25, 0xbe, 0x47, 0xf5, 0x33, 0x42, 0xcf, 0x77, 0xda,
	0x31, 0x43, 0xba, 0x61, 0xed, 0xef, 0x7a, 0xe4, 0xe0, 0x85, 0x60, 0xed, 0x0c, 0x48, 0x09, 0x43,
	0x97, 0xe2, 0x71, 0x86, 0x94, 0xa1, 0xbf, 0x0b, 0xb1, 0x63, 0xad, 0xb7, 0xfd, 0x2e, 0x89, 0x70,
	0x37, 0x88, 0x0e, 0xf9, 0x15, 0xa1, 0x2f, 0x70, 0x8e, 0xfa, 0xb5, 0xcf, 0x0a, 0x30, 0xc6, 0xa7,
	0x87, 0x4f, 0xc1, 0xd9, 0x98, 0xe2, 0x50, 0x3f, 0x2b, 0x0e, 0xb1, 0x96, 0x30, 0x24, 0xf6, 0x29,
	0x43, 0x17, 0xa5, 0x2c, 0x8a, 0xc3, 0xb2, 0x8a, 0xf9, 0x32, 0x64, 0x08, 0x3e, 0x7c, 0x0d, 0x66,
	0x02, 0x8b, 0xd2, 0x7d, 0x3f, 0x74, 0xf4, 0x73, 0x22, 0xd6, 0xe3, 0x84, 0x21, 0x85, 0xa5, 0x0c,
	0xe9, 0x22, 0x5e, 0x0e, 0x94, 0x63, 0xc2, 0x51, 0xd8, 0x50, 0xbe, 0xb0, 0x0b, 0x2a, 0xbc, 0x22,
	0x4d, 0x5e, 0x92, 0xfa, 0xd4, 0x92, 0xb6, 0x32, 0xbf, 0xb6, 0x58, 0x97, 0xa5, 0x5a, 0xdf, 0x88,
	0xa3, 0xf6, 0x7f, 0x7c, 0x07, 0xcb, 0x74, 0x56, 0xb6, 0x53, 0xe9, 0x72, 0x60, 0x28, 0xdd, 0x28,
	0x6c, 0x28, 0x5f, 0x88, 0xc1, 0x74, 0x4c, 0xb1, 0x19, 0xb9, 0x54, 0x9f, 0x16, 0xe5, 0xfc, 0xfc,
	0x98, 0xa1, 0x0a, 0xbf, 0x58, 0x8a, 0x5f, 0x3e, 0x7f, 0x91, 0x30, 0x34, 0x15, 0x8b, 0x55, 0xca,
	0xd0, 0xbc, 0xc8, 0x12, 0xb9, 0x54, 0x96, 0x75, 0xd2, 0xab, 0xcd, 0xe4, 0x9b, 0xb4, 0x57, 0xcb,
	0x78, 0x47, 0xfd, 0xda, 0xc0, 0xdd, 0x10, 0xa0, 0x4b, 0x79, 0x1a, 0x2b, 0x20, 0x66, 0x07, 0x1f,
	0xea, 0x33, 0xe2, 0xc2, 0x78, 0x9a, 0xa9, 0x8d, 0x9d, 0xad, 0x6d, 0x7c, 0xc8, 0x73, 0x58, 0x01,
	0xd9, 0xc6, 0x87, 0x29, 0x43, 0x97, 0xe5, 0x49, 0x02, 0xd2, 0xc1, 0x87, 0xe5, 0x73, 0x2c, 0x0e,
	0x83, 0x47, 0xfd, 0x5a, 0x16, 0xc1, 0xc8, 0xfc, 0xe1, 0xb7, 0x1a, 0xb8, 0x44, 0x3c, 0x8a, 0xed,
	0x38, 0xc4, 0xa6, 0xe5, 0x74, 0x89, 0x67, 0x5a, 0xb6, 0xcd, 0xfb, 0xa8, 0x22, 0x0e, 0x67, 0x26,
	0x0c, 0x5d, 0xc8, 0x09, 0x1b, 0xdc, 0xbe, 0x21, 0xcc, 0x29, 0x43, 0x37, 0x44, 0xe2, 0x31, 0xb6,
	0xb2, 0x8a, 0x6b, 0x7f, 0xc8, 0x30, 0xc6, 0x05, 0x87, 0xdb, 0xe0, 0x5c, 0xd4, 0xc6, 0x5d, 0xac,
	0x03, 0x71, 0xf4, 0x07, 0x09, 0x43, 0x12, 0x48, 0x19, 0xba, 0x26, 0xef, 0x94, 0xef, 0x0a, 0xad,
	0x9b, 0x2d, 0x78, 0xcf, 0x4e, 0x67, 0x6b, 0x43, 0xba, 0xc0, 0x5d, 0x50, 0x71, 0x70, 0x33, 0x6e,
	0xb5, 0x88, 0xd7, 0xd2, 0x67, 0xc5, 0xa9, 0x1e, 0x26, 0x0c, 0x0d, 0x40, 0x55, 0xcd, 0x0a, 0x51,
	0x9f, 0x6b, 0xbe, 0x0c, 0x19, 0x03, 0x27, 0xf8, 0x93, 0x06, 0x74, 0x75, 0x73, 0xb4, 0x43, 0x02,
	0xb3, 0xed, 0xd3, 0xc8, 0xb4, 0xdb, 0xd8, 0xee, 0xe8, 0xe7, 0x45, 0x9a, 0xff, 0xf3, 0xbe, 0xce,
	0x39, 0x2f, 0x3a, 0x24, 0x78, 0xe6, 0xd3, 0x48, 0x10, 0x54, 0x5f, 0x8f, 0xb5, 0x0e, 0xf5, 0xf5,
	0x17, 0x38, 0x69, 0xaf, 0x36, 0x3e, 0x89, 0x31, 0x02, 0x6f, 0x72, 0x18, 0xfe, 0xa0, 0x81, 0xbf,
	0x0d, 0xbe, 0xb9, 0xeb, 0xfa, 0xfb, 0xe6, 0x5e, 0x68, 0x75, 0xb1, 0xe9, 0xfa, 0x96, 0xc3, 0x2f,
	0x69, 0x4e, 0xa8, 0x7f, 0x93, 0x30, 0x74, 0x45, 0x7d, 0x1d, 0x4e, 0x7b, 0xca, 0x59, 0xcf, 0x25,
	0x29, 0x65, 0xe8, 0x56, 0xb9, 0x00, 0x86, 0x19, 0xe5, 0x53, 0xdc, 0xf8, 0x13, 0x3c, 0xe3, 0xf3,
	0xe9, 0xe0, 0x37, 0x1a, 0xb8, 0x4c, 0xb1, 0xe7, 0x98, 0x4d, 0x8b, 0x12, 0xdb, 0x14, 0x1d, 0x1f,
	0x84, 0x7e, 0x37, 0x88, 0xf4, 0x79, 0x21, 0x77, 0x97, 0x57, 0x2a, 0x67, 0x34, 0x38, 0x81, 0x37,
	0xfe, 0x8e, 0x30, 0xa7, 0x0c, 0x55, 0x85, 0xd0, 0x31, 0x36, 0xf5, 0x9d, 0xf5, 0xcf, 0x19, 0x8d,
	0x71, 0x21, 0xe1, 0x1e, 0x58, 0xdc, 0xc7, 0x4d, 0xae, 0xc1, 0x33, 0xf9, 0xef, 0x9b, 0x49, 0x1c,
	0x7d, 0x41, 0x94, 0xea, 0x3f, 0x12, 0x86, 0xe6, 0x73, 0xdb, 0x2e, 0xc5, 0xe1, 0x96, 0xa3, 0xca,
	0xab, 0x0c, 0x8b, 0xf2, 0x2a, 0x43, 0xc6, 0xd0, 0x1e, 0xbe, 0x03, 0x0a, 0x31, 0xc3, 0x80, 0x67,
	0x59, 0x14, 0x59, 0x5e, 0x25, 0x0c, 0x9d, 0xcf, 0x2d, 0x46, 0x20, 0x72, 0xdc, 0x2c, 0xe5, 0xe0,
	0x60, 0xa1, 0x3d, 0x5c, 0xdf, 0xb6, 0x5c, 0x5e, 0x9f, 0xe2, 0x2d, 0x2d, 0x92, 0x4e, 0x7b, 0xb5,
	0x8a, 0xb2, 0x1a, 0x25, 0x13, 0xfc, 0xa0, 0x81, 0x05, 0x95, 0xdf, 0x0f, 0x49, 0x8b, 0x78, 0xfa,
	0x5f, 0x84, 0x80, 0xfd, 0xe2, 0x31, 0xff, 0x2b, 0x2c, 0x29, 0x43, 0x0f, 0x4a, 0x12, 0x24, 0x5c,
	0x10, 0xd1, 0x8e, 0xa2, 0x80, 0xae, 0xaf, 0xae, 0xaa, 0x74, 0xf2, 0x99, 0x2d, 0xde, 0x83, 0xf4,
	0x39, 0xed, 0xd5, 0x2e, 0x8f, 0x27, 0x1b, 0x43, 0x4c, 0xf8, 0xa3, 0x06, 0x2e, 0x2a, 0x89, 0x76,
	0x88, 0x1d, 0xec, 0x45, 0xc4, 0x72, 0xa9, 0x0e, 0x97, 0xce, 0xac, 0xcc, 0xae, 0x5d, 0xcd, 0x1f,
	0x82, 0x57, 0x19, 0x67, 0x53, 0x51, 0x1a, 0x7b, 0x1f, 0x19, 0x9a, 0x48, 0x18, 0xba, 0x68, 0xee,
	0x8f, 0x18, 0xa9, 0x7a, 0x22, 0x46, 0x6d, 0xe2, 0x89, 0x18, 0x85, 0xd3, 0x5e, 0x6d, 0x6c, 0x24,
	0xe3, 0xc2, 0x18, 0x70, 0xf9, 0xb7, 0x29, 0x00, 0x47, 0x35, 0xc1, 0xc7, 0x60, 0x92, 0xc8, 0x31,
	0xa9, 0xd2, 0xa8, 0x1f, 0x33, 0x34, 0xb9, 0xf5, 0x24, 0x61, 0x68, 0x92, 0xf0, 0x0f, 0x3c, 0x27,
	0xdb, 0xcd, 0x51, 0x45, 0x3b, 0x9d, 0xad, 0x8f, 0xfa, 0xb5, 0xc9, 0xad, 0x27, 0xc6, 0x24, 0x71,
	0xe0, 0x3f, 0xc1, 0x39, 0x59, 0x27, 0x72, 0x0a, 0x5a, 0xe1, 0x0f, 0x76, 0x28, 0xeb, 0x63, 0x41,
	0xb8, 0xf3, 0x8d, 0x0a, 0x50, 0x51, 0x3b, 0x43, 0xb0, 0xe0, 0x0e, 0x98, 0xf1, 0x88, 0xdd, 0xf1,
	0xac, 0x2e, 0xce, 0xe6, 0x96, 0xfb, 0xfc, 0xdd, 0xcc, 0xb1, 0x94, 0xa1, 0x0b, 0x22, 0x4a, 0x0e,
	0xa8, 0x48, 0x73, 0x25, 0xc4, 0x50, 0x1e, 0xb0, 0x03, 0x16, 0x82, 0xb8, 0xe9, 0x12, 0x9b, 0xbf,
	0x64, 0xa6, 0xed, 0x53, 0x9c, 0xcd, 0x12, 0x9b, 0x09, 0x43, 0x73, 0xd2, 0xb4, 0x8d, 0x0f, 0x37,
	0x7d, 0x3a, 0x78, 0x95, 0x4b, 0xa8, 0x4a, 0x01, 0x47, 0x61, 0xa3, 0x1c, 0x00, 0xfe, 0x0f, 0x00,
	0x4a, 0x5a, 0x9e, 0x69, 0xfb, 0xb1, 0x17, 0x89, 0x39, 0x63, 0x4e, 0xfe, 0xd4, 0x73, 0x74, 0x93,
	0x83, 0xaa, 0x17, 0x15, 0x32, 0xf8, 0xa9, 0x2f, 0x43, 0xc6, 0xc0, 0x09, 0xbe, 0x06, 0x20, 0x0a,
	0x2d, 0x8f, 0x06, 0x7e, 0x18, 0x51, 0x7d, 0x6a, 0xe9, 0xcc, 0x4a, 0xa5, 0xb1, 0x9e, 0x30, 0x54,
	0x40, 0x53, 0x86, 0x2e, 0xc9, 0x87, 0x49, 0x41, 0x2a, 0xf2, 0xc2, 0x10, 0x66, 0x14, 0xfc, 0xb8,
	0xe6, 0x10, 0xbf, 0x89, 0x49, 0x88, 0xcd, 0xf8, 0x6d, 0x36, 0x51, 0x08, 0xcd, 0x19, 0xba, 0xfb,
	0x56, 0x69, 0x56, 0xc8, 0x40, 0x73, 0x19, 0x32, 0x06, 0x4e, 0xf0, 0x2b, 0x30, 0x6b, 0x87, 0xd8,
	0x8a, 0xb0, 0xc9, 0x47, 0x79, 0x31, 0x43, 0xf0, 0x76, 0x90, 0x73, 0x7e, 0x3d, 0x9f, 0xf3, 0xeb,
	0x2f, 0xf3, 0x39, 0xbf, 0xd1, 0xc8, 0xda, 0x01, 0x48, 0x37, 0x6e, 0x50, 0x87, 0x1a, 0x40, 0x32,
	0xf5, 0xfb, 0x5f, 0x91, 0xc6, 0x0f, 0x36, 0x84, 0x1b, 0x05, 0x5f, 0xf8, 0xb5, 0x06, 0xe6, 0x5c,
	0x8b, 0x46, 0xa6, 0x98, 0x96, 0xb8, 0x86, 0xca, 0x17, 0x35, 0xfc, 0x2b, 0xd3, 0x30, 0xcb, 0x1d,
	0xf9, 0x40, 0x24, 0x45, 0xc8, 0x11, 0xa7, 0x80, 0x95, 0x54, 0x2c, 0x0e, 0x1b, 0x8c, 0xa2, 0x7b,
	0x63, 0xfb, 0xe3, 0xa7, 0xea, 0x44, 0xff, 0x53, 0x75, 0xe2, 0xe3, 0x71, 0x55, 0xeb, 0x1f, 0x57,
	0xb5, 0xf7, 0x27, 0xd5, 0x89, 0x0f, 0x27, 0x55, 0xad, 0x7f, 0x52, 0x9d, 0xf8, 0xe5, 0xa4, 0x3a,
	0xf1, 0xfa, 0x56, 0x8b, 0x44, 0xed, 0xb8, 0x59, 0xb7, 0xfd, 0xee, 0x2a, 0x3d, 0xf4, 0xec, 0xa8,
	0x4d, 0xbc, 0x56, 0x61, 0x35, 0xf8, 0xeb, 0xd3, 0x9c, 0x12, 0xa2, 0xef, 0xfd, 0x1e, 0x00, 0x00,
	0xff, 0xff, 0xe4, 0x5b, 0x8a, 0x5e, 0x5b, 0x0d, 0x00, 0x00,
}

func (m *GUIConfiguration) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GUIConfiguration) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GUIConfiguration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WebauthnCredentials) > 0 {
		for iNdEx := len(m.WebauthnCredentials) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WebauthnCredentials[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGuiconfiguration(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x92
		}
	}
	if len(m.WebauthnOrigin) > 0 {
		i -= len(m.WebauthnOrigin)
		copy(dAtA[i:], m.WebauthnOrigin)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.WebauthnOrigin)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.WebauthnRpId) > 0 {
		i -= len(m.WebauthnRpId)
		copy(dAtA[i:], m.WebauthnRpId)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.WebauthnRpId)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.WebauthnUserId) > 0 {
		i -= len(m.WebauthnUserId)
		copy(dAtA[i:], m.WebauthnUserId)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.WebauthnUserId)))
		i--
		dAtA[i] = 0x7a
	}
	if m.SendBasicAuthPrompt {
		i--
		if m.SendBasicAuthPrompt {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.InsecureAllowFrameLoading {
		i--
		if m.InsecureAllowFrameLoading {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.InsecureSkipHostCheck {
		i--
		if m.InsecureSkipHostCheck {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.Debugging {
		i--
		if m.Debugging {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if len(m.Theme) > 0 {
		i -= len(m.Theme)
		copy(dAtA[i:], m.Theme)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.Theme)))
		i--
		dAtA[i] = 0x52
	}
	if m.InsecureAdminAccess {
		i--
		if m.InsecureAdminAccess {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.APIKey) > 0 {
		i -= len(m.APIKey)
		copy(dAtA[i:], m.APIKey)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.APIKey)))
		i--
		dAtA[i] = 0x42
	}
	if m.RawUseTLS {
		i--
		if m.RawUseTLS {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.AuthMode != 0 {
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(m.AuthMode))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Password) > 0 {
		i -= len(m.Password)
		copy(dAtA[i:], m.Password)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.Password)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RawUnixSocketPermissions) > 0 {
		i -= len(m.RawUnixSocketPermissions)
		copy(dAtA[i:], m.RawUnixSocketPermissions)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.RawUnixSocketPermissions)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RawAddress) > 0 {
		i -= len(m.RawAddress)
		copy(dAtA[i:], m.RawAddress)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.RawAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *WebauthnCredential) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebauthnCredential) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WebauthnCredential) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.LastUseTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.LastUseTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintGuiconfiguration(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x4a
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CreateTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CreateTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintGuiconfiguration(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x42
	if m.RequireUv {
		i--
		if m.RequireUv {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.Transports) > 0 {
		for iNdEx := len(m.Transports) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Transports[iNdEx])
			copy(dAtA[i:], m.Transports[iNdEx])
			i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.Transports[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.SignCount != 0 {
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(m.SignCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PublicKeyCose) > 0 {
		i -= len(m.PublicKeyCose)
		copy(dAtA[i:], m.PublicKeyCose)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.PublicKeyCose)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Nickname) > 0 {
		i -= len(m.Nickname)
		copy(dAtA[i:], m.Nickname)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.Nickname)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RpId) > 0 {
		i -= len(m.RpId)
		copy(dAtA[i:], m.RpId)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.RpId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintGuiconfiguration(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGuiconfiguration(dAtA []byte, offset int, v uint64) int {
	offset -= sovGuiconfiguration(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GUIConfiguration) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	l = len(m.RawAddress)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	l = len(m.RawUnixSocketPermissions)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	if m.AuthMode != 0 {
		n += 1 + sovGuiconfiguration(uint64(m.AuthMode))
	}
	if m.RawUseTLS {
		n += 2
	}
	l = len(m.APIKey)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	if m.InsecureAdminAccess {
		n += 2
	}
	l = len(m.Theme)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	if m.Debugging {
		n += 2
	}
	if m.InsecureSkipHostCheck {
		n += 2
	}
	if m.InsecureAllowFrameLoading {
		n += 2
	}
	if m.SendBasicAuthPrompt {
		n += 2
	}
	l = len(m.WebauthnUserId)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	l = len(m.WebauthnRpId)
	if l > 0 {
		n += 2 + l + sovGuiconfiguration(uint64(l))
	}
	l = len(m.WebauthnOrigin)
	if l > 0 {
		n += 2 + l + sovGuiconfiguration(uint64(l))
	}
	if len(m.WebauthnCredentials) > 0 {
		for _, e := range m.WebauthnCredentials {
			l = e.ProtoSize()
			n += 2 + l + sovGuiconfiguration(uint64(l))
		}
	}
	return n
}

func (m *WebauthnCredential) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	l = len(m.RpId)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	l = len(m.Nickname)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	l = len(m.PublicKeyCose)
	if l > 0 {
		n += 1 + l + sovGuiconfiguration(uint64(l))
	}
	if m.SignCount != 0 {
		n += 1 + sovGuiconfiguration(uint64(m.SignCount))
	}
	if len(m.Transports) > 0 {
		for _, s := range m.Transports {
			l = len(s)
			n += 1 + l + sovGuiconfiguration(uint64(l))
		}
	}
	if m.RequireUv {
		n += 2
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CreateTime)
	n += 1 + l + sovGuiconfiguration(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.LastUseTime)
	n += 1 + l + sovGuiconfiguration(uint64(l))
	return n
}

func sovGuiconfiguration(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGuiconfiguration(x uint64) (n int) {
	return sovGuiconfiguration(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GUIConfiguration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGuiconfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GUIConfiguration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GUIConfiguration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawUnixSocketPermissions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawUnixSocketPermissions = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthMode", wireType)
			}
			m.AuthMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuthMode |= AuthMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawUseTLS", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RawUseTLS = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field APIKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.APIKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InsecureAdminAccess", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.InsecureAdminAccess = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Theme", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Theme = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Debugging", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Debugging = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InsecureSkipHostCheck", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.InsecureSkipHostCheck = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InsecureAllowFrameLoading", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.InsecureAllowFrameLoading = bool(v != 0)
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendBasicAuthPrompt", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SendBasicAuthPrompt = bool(v != 0)
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebauthnUserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebauthnUserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebauthnRpId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebauthnRpId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebauthnOrigin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebauthnOrigin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebauthnCredentials", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebauthnCredentials = append(m.WebauthnCredentials, WebauthnCredential{})
			if err := m.WebauthnCredentials[len(m.WebauthnCredentials)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGuiconfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebauthnCredential) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGuiconfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebauthnCredential: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebauthnCredential: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RpId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nickname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nickname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKeyCose", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKeyCose = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignCount", wireType)
			}
			m.SignCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transports", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transports = append(m.Transports, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequireUv", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequireUv = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CreateTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUseTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.LastUseTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGuiconfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGuiconfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGuiconfiguration(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGuiconfiguration
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGuiconfiguration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGuiconfiguration
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGuiconfiguration
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGuiconfiguration
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGuiconfiguration        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGuiconfiguration          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGuiconfiguration = fmt.Errorf("proto: unexpected end of group")
)
