#!/bin/bash

addgroup --system syncthing
adduser --system --home /var/lib/syncthing-discosrv --ingroup syncthing syncthing-discosrv
adduser --system --home /var/lib/syncthing-relaysrv --ingroup syncthing syncthing-relaysrv
