name: golangci-lint
on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: ensure asset generation
        run: go run build.go
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          only-new-issues: true
